# Dataset root directory
path: TutorialData

# Image folders for each split
train: Train/img # 80%
val: Validate/img # 10%
test: Test/img   # 10%

# Classes
names:
  0: blue
  1: large orange
  2: small orange
  3: other
  4: yellow
          