# Dataset root directory
path: TutorialData

# Image folders for each split
train: Train/images # 80%
val: Validate/images # 10%
test: Test/images   # 10%

# Classes
names:
  0: blue
  1: large orange
  2: small orange
  3: other
  4: yellow
          